Demo.Zoom.Web/Models/ZoomConfigurationModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Demo.Zoom.Web.Models
{
    public class ZoomConfigurationModel
    {
        public string ApiKey { get; set; }
        public string ApiSecret { get; set; }
    }
}

Demo.Zoom.Web/Controllers/HomeController.cs
using System.Web.Mvc;

namespace Demo.Zoom.Web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult ThankYou()
        {
            ViewBag.Message = "Thanks for joining meeting.";

            return View();
        }
    }
}

Demo.Zoom.Web/Controllers/MeetingController.cs
using System.Configuration;
using System.Threading.Tasks;
using System.Web.Mvc;
using Zoom.Demo;

namespace Demo.Zoom.Web.Controllers
{
    public class MeetingController : Controller
    {
        private readonly IMeetingClient meetingClient;

        public MeetingController(IMeetingClient meetingClient)
        {
            this.meetingClient = meetingClient;
        }

        // GET: Meeting
        public async Task<ActionResult> Index()
        {
            var userMeeting =
                await meetingClient.GetUserMeetings(ConfigurationManager.AppSettings["userId"], "upcoming",true);
            return View(userMeeting);
        }

        public ActionResult ListAll()
        {
            return View();
        }
    }
}

Demo.Zoom.Web/Controllers/WebinarController.cs
using System.Configuration;
using System.Threading.Tasks;
using System.Web.Mvc;
using Zoom.Demo.Clients;

namespace Demo.Zoom.Web.Controllers
{
    public class WebinarController : Controller
    {
        private readonly IWebinarClient webinarClient;

        public WebinarController(IWebinarClient webinarClient)
        {
            this.webinarClient = webinarClient;
        }

        // GET: Webinar
        public async Task<ActionResult> Index()
        {
            var webinars = await webinarClient.GetUserWebinars(ConfigurationManager.AppSettings["userId"], true,true);
            return View(webinars);
        }
    }
}

Demo.Zoom.Web/Controllers/ZoomController.cs
using System.Configuration;
using System.Web.Mvc;
using Demo.Zoom.Web.Helper;
using Demo.Zoom.Web.Models;

namespace Demo.Zoom.Web.Controllers
{
    /// <summary>
    ///     Zoom Meeting Controller : Integrated zoom SDK via CDN
    ///     <ref>https://marketplace.zoom.us/docs/sdk/native-sdks/web/getting-started/integrate</ref>
    /// </summary>
    public class ZoomController : Controller
    {
        // GET: Zoom
        public ActionResult Index()
        {
            var model = new ZoomConfigurationModel()
            {
                ApiKey = ConfigurationManager.AppSettings["zoom-client-option:apiKey"],
                ApiSecret = ConfigurationManager.AppSettings["zoom-client-option:apiSecret"]
            };
            return View(model);
        }

        public ActionResult Webinar()
        {
            var model = new ZoomConfigurationModel()
            {
                ApiKey = ConfigurationManager.AppSettings["zoom-client-option:apiKey"],
                ApiSecret = ConfigurationManager.AppSettings["zoom-client-option:apiSecret"]
            };
            return View(model);
        }

        [HttpGet]
        public JsonResult GetSignature(string meetingId, string roleId)
        {
            var data = new {result = Signature.GetToken(meetingId, roleId)};
            return Json(data, JsonRequestBehavior.AllowGet);
        }
    }
}

Demo.Zoom.Web/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Demo.Zoom.Web/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br/>
    Redmond, WA 98052-6399<br/>
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br/>
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Demo.Zoom.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>BBC Zoom Demo</h1>
    <p class="lead">This sample application is to demonstrate the zoom integration with Asp.Net MVC framework.</p>
    <p>
        @Html.ActionLink("Start meeting", "Index", new {controller = "Zoom"}, new {@class = "btn btn-primary btn-lg"})

    </p>
</div>
<div class="row">
    <div class="col-md-6">
        <h2>Get started with meeting</h2>
        <p>
            Feature to attend zoom meeting with in the website.
            This feature is developed only for demo purpose.
        </p>
        <p>
            @Html.ActionLink("Start meeting", "Index", new {controller = "Zoom"}, new {@class = "btn btn-primary btn-lg"})
        </p>
    </div>
    <div class="col-md-6">
        <h2>Get started with webinar</h2>
        <p>
            Feature to attend zoom webinar with in the website.
            This feature is developed only for demo purpose.
        </p>
        <p>
            @Html.ActionLink("Start webinar", "Webinar", new {controller = "Zoom"}, new {@class = "btn btn-primary btn-lg"})

        </p>
    </div>
</div>

Demo.Zoom.Web/Views/Home/ThankYou.cshtml
@{
    ViewBag.Title = "ThankYou";
}

<h3>@ViewBag.Message</h3>


<p>Join new meeting @Html.ActionLink("here", "Index", "Zoom")</p>

Demo.Zoom.Web/Views/Meeting/Index.cshtml
@model Zoom.Demo.Entity.UserMeetings
@{
    ViewBag.Title = "Index";
}

<link href="~/Content/meetings.css" rel="stylesheet"/>

<div class="row">
    <div class="col-md-12">
        <!-- Nav tabs -->
        <div class="card">
            <div class="tab-content">


                <div role="tabpanel" class="tab-pane active" id="day1">
                    <section class="webinar-listing-section">
                        <div id="upcoming-webinars" class="webinar-listing content-block-extra">
                            <h2 class="metting-title"> Meetings </h2>
                            <div class="slider webinar-slider">
                                <div class="row">
                                    <ul class="webinar-slider-list">
                                        @*Meeting Widget*@
                                        @foreach (var meeting in Model.Meetings)
                                        {
                                            @Html.Partial("_MeetingWidget", meeting)
                                            ;
                                        }

                                    </ul>
                                </div>
                            </div>
                        </div>
                    </section>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="https://source.zoom.us/1.7.9/lib/vendor/react.min.js"></script>
<script src="https://source.zoom.us/1.7.9/lib/vendor/react-dom.min.js"></script>
<script src="https://source.zoom.us/1.7.9/lib/vendor/redux.min.js"></script>
<script src="https://source.zoom.us/1.7.9/lib/vendor/redux-thunk.min.js"></script>
<script src="https://source.zoom.us/1.7.9/lib/vendor/jquery.min.js"></script>
<script src="https://source.zoom.us/1.7.9/lib/vendor/lodash.min.js"></script>

<script src="https://source.zoom.us/zoom-meeting-1.7.9.min.js"></script>
<script src="~/Scripts/zoom/tool.js"></script>
<script src="~/Scripts/zoom/index.js"></script>
<script type="text/javascript">
    $(".input").focus(function() {
        $(this).parent().addClass("focus");
    });
    var API_KEY = "api-key";
    var API_SECRET = "api-secret";

    function join_click(meetingId, userName, role, meetingPassword='') {
        var meetConfig = {
            apiKey: API_KEY,
            apiSecret: API_SECRET,
            meetingNumber: parseInt(meetingId),
            userName: userName,
            passWord: meetingPassword,
            leaveUrl: '@Url.Action("Index", "Home")',
            role: parseInt(role)
        };

        GetSignature(meetConfig.meetingNumber, meetConfig.role).then(function(data) {
            console.log(data);
            JoinMeeting(meetConfig, data.result);
        });
    }

    function GetSignature(meetingId, roleId) {
        return $.ajax({
            url: '@Url.Action("GetSignature", "Zoom")',
            type: 'GET',
            dataType: 'json',
            cache: false,
            data: { 'meetingId': meetingId, 'roleId': roleId }
        });
    }

    function JoinMeeting(meetConfig, signature) {
        //console.log('meetConfig', meetConfig);
        //console.log('signature', signature);

        ZoomMtg.init({
            leaveUrl: '@Url.Action("ThankYou", "Home")',
            success: function() {
                ZoomMtg.join(
                    {
                        meetingNumber: meetConfig.meetingNumber,
                        userName: meetConfig.userName,
                        signature: signature,
                        apiKey: meetConfig.apiKey,
                        passWord: meetConfig.passWord,
                        success: function(res) {
                            // $('#nav-tool').hide();
                            console.log('join meeting success');
                        },
                        error: function(res) {
                            console.log(res);
                        }
                    }
                );
            },
            error: function(res) {
                console.log(res);
            }
        });
    }

    $('[id^="partClick-"]').click(function(e) {
        e.preventDefault();
       
        var id = this.id.substring('partClick-'.length, this.id.length);
        var target = $("#participant-"+id);
      
        if (target.is(':visible')) {
            target.attr("style", "display:none");
        } else {
            target.attr("style", "display:block");
        }
    });
</script>

Demo.Zoom.Web/Views/Webinar/Index.cshtml
@model Zoom.Demo.Entity.UserWebinars
@{
    ViewBag.Title = "Index";
}

<link href="~/Content/meetings.css" rel="stylesheet"/>

<div class="row">
    <div class="col-md-12">
        <!-- Nav tabs -->
        <div class="card">
            <div class="tab-content">
                <div role="tabpanel" class="tab-pane active" id="day1">
                    <section class="webinar-listing-section">
                        <div id="upcoming-webinars" class="webinar-listing content-block-extra">
                            <h2 class="metting-title"> Webinars </h2>
                            <div class="slider webinar-slider">
                                <div class="row">
                                    <ul class="webinar-slider-list">
                                        @foreach (var webinar in Model.Webinars)
                                        {
                                            @Html.Partial("_WebinarWidget", webinar)
                                            ;
                                        }

                                    </ul>
                                </div>
                            </div>
                        </div>
                    </section>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="https://source.zoom.us/1.7.9/lib/vendor/react.min.js"></script>
<script src="https://source.zoom.us/1.7.9/lib/vendor/react-dom.min.js"></script>
<script src="https://source.zoom.us/1.7.9/lib/vendor/redux.min.js"></script>
<script src="https://source.zoom.us/1.7.9/lib/vendor/redux-thunk.min.js"></script>
<script src="https://source.zoom.us/1.7.9/lib/vendor/jquery.min.js"></script>
<script src="https://source.zoom.us/1.7.9/lib/vendor/lodash.min.js"></script>

<script src="https://source.zoom.us/zoom-meeting-1.7.9.min.js"></script>
<script src="~/Scripts/zoom/tool.js"></script>
<script src="~/Scripts/zoom/index.js"></script>

<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script type="text/javascript">
    $(".input").focus(function() {
        $(this).parent().addClass("focus");
    });
    var API_KEY = "api-key";
    var API_SECRET = "api-secret";

    function join_click(meetingId, userName, meetingPassword, role, userEmail) {
        var meetConfig = {
            apiKey: API_KEY,
            apiSecret: API_SECRET,
            meetingNumber: parseInt(meetingId),
            userName: userName,
            passWord: meetingPassword,
            userEmail: userEmail,
            leaveUrl: '@Url.Action("Index", "Home")',
            role: parseInt(role)
        };

        GetSignature(meetConfig.meetingNumber, meetConfig.role).then(function(data) {
            console.log(data);
            JoinMeeting(meetConfig, data.result);
        });
    }

    function GetSignature(meetingId, roleId) {
        return $.ajax({
            url: '@Url.Action("GetSignature", "Zoom")',
            type: 'GET',
            dataType: 'json',
            cache: false,
            data: { 'meetingId': meetingId, 'roleId': roleId }
        });
    }

    function JoinMeeting(meetConfig, signature) {
        //console.log('meetConfig', meetConfig);
        //console.log('signature', signature);

        ZoomMtg.init({
            leaveUrl: '@Url.Action("ThankYou", "Home")',
            success: function() {
                ZoomMtg.join(
                    {
                        meetingNumber: meetConfig.meetingNumber,
                        userName: meetConfig.userName,
                        userEmail: meetConfig.userEmail,
                        signature: signature,
                        apiKey: meetConfig.apiKey,
                        passWord: meetConfig.passWord,
                        success: function(res) {
                            // $('#nav-tool').hide();
                            console.log('join meeting success');
                        },
                        error: function(res) {
                            console.log(res);
                        }
                    }
                );
            },
            error: function(res) {
                console.log(res);
            }
        });
    }

    $('[id^="partClick-"]').click(function(e) {
        e.preventDefault();
       
        var id = this.id.substring('partClick-'.length, this.id.length);
        var target = $("#participant-"+id);
       
        if (target.is(':visible')) {
            target.attr("style", "display:none");
        } else {
            target.attr("style", "display:block");
        }
    });

   
</script>


Demo.Zoom.Web/Views/Zoom/Index.cshtml
@model Demo.Zoom.Web.Models.ZoomConfigurationModel
@{
    ViewBag.Title = "Index";
}
@* Bootstrap form template : https://bootsnipp.com/snippets/nNZ47*@
<link href="~/Content/zoom.css" rel="stylesheet"/>
<div class="container-fluid">
    <div class="container">
        <div id="formMeeting" class="formBox">
            <form>
                <div class="row">
                    <div class="col-sm-12">
                        <h1>Join Meeting</h1>
                    </div>
                </div>

                <div class="row">
                    <div class="col-sm-6">
                        <div class="inputBox ">
                            <div class="inputText">Display Name</div>
                            <input type="text" name="display_name" id="display_name" class="input">
                        </div>
                    </div>

                    <div class="col-sm-6">
                        <div class="inputBox">
                            <div class="inputText">Meeting Number</div>
                            <input type="text" name="meeting_number" id="meeting_number" class="input">
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-sm-6">
                        <div class="inputBox">
                            <div class="inputText">Meeting Password</div>
                            <input type="text" name="meeting_pwd" id="meeting_pwd" class="input">
                        </div>
                    </div>

                    <div class="col-sm-6">
                        <label class="inputLabel">Meeting Role</label>
                        <div class="inputBox">

                            <select id="meeting_role" class="sdk-select">
                                <option value="0">Attendee</option>
                                <option value="1">Host</option>
                                <option value="5">Assistant</option>
                            </select>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-sm-12">
                        <label class="inputLabel">Language</label>
                        <div class="inputBox">
                            <select id="meeting_lang" class="sdk-select">
                                <option value="en-US">English</option>
                                <option value="de-DE">German Deutsch</option>
                                <option value="es-ES">Spanish Español</option>
                                <option value="fr-FR">French Français</option>
                                <option value="jp-JP">Japanese 日本語</option>
                                <option value="pt-PT">Portuguese Portuguese</option>
                                <option value="ru-RU">Russian Русский</option>
                                <option value="zh-CN">Chinese 简体中文</option>
                                <option value="zh-TW">Chinese 繁体中文</option>
                                <option value="ko-KO">Korean 한국어</option>
                            </select>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-sm-12">
                        <button type="submit" class="btn btn-primary" id="join_meeting">Join</button>
                        <button type="submit" class="btn btn-primary" id="clear_all">Clear</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<script src="https://source.zoom.us/1.9.5/lib/vendor/react.min.js"></script>
<script src="https://source.zoom.us/1.9.5/lib/vendor/react-dom.min.js"></script>
<script src="https://source.zoom.us/1.9.5/lib/vendor/redux.min.js"></script>
<script src="https://source.zoom.us/1.9.5/lib/vendor/redux-thunk.min.js"></script>
<script src="https://source.zoom.us/1.9.5/lib/vendor/lodash.min.js"></script>

<script src="https://source.zoom.us/zoom-meeting-1.9.5.min.js"></script>
<script src="~/Scripts/zoom/tool.js"></script>
<script src="~/Scripts/zoom/index.js"></script>
<script type="text/javascript">
    $(".input").focus(function() {
        $(this).parent().addClass("focus");
    });
    var API_KEY = '@Model.ApiKey';
    var API_SECRET = '@Model.ApiSecret';

    document.getElementById('join_meeting').addEventListener('click',
        function(e) {

            e.preventDefault();

            if (!this.form.checkValidity()) {
                alert("Enter Name and Meeting Number");
                return false;
            }

            //testTool.setCookie("meeting_number", meetConfig.meetingNumber);
            //testTool.setCookie("meeting_pwd", meetConfig.passWord);

            var meetConfig = {
                apiKey: API_KEY,
                apiSecret: API_SECRET,
                meetingNumber: parseInt(document.getElementById('meeting_number').value),
                userName: document.getElementById('display_name').value,
                passWord: document.getElementById('meeting_pwd').value,
                leaveUrl: '@Url.Action("Index", "Home")',
                role: parseInt(document.getElementById('meeting_role').value, 10)
            };

            GetSignature(meetConfig.meetingNumber, meetConfig.role).then(function(data) {
                //console.log(data);
                JoinMeeting(meetConfig, data.result);
            });

        });

    document.getElementById('clear_all').addEventListener('click',
        function(e) {
            testTool.deleteAllCookies();
            document.getElementById('display_name').value = '';
            document.getElementById('meeting_number').value = '';
            document.getElementById('meeting_pwd').value = '';
            document.getElementById('meeting_lang').value = 'en-US';
            document.getElementById('meeting_role').value = 0;
        });

    function GetSignature(meetingId, roleId) {
        return $.ajax({
            url: '@Url.Action("GetSignature", "Zoom")',
            type: 'GET',
            dataType: 'json',
            cache: false,
            data: { 'meetingId': meetingId, 'roleId': roleId }
        });
    }

    function JoinMeeting(meetConfig, signature) {
        //console.log('meetConfig', meetConfig);
        //console.log('signature', signature);

        ZoomMtg.init({
            leaveUrl: '@Url.Action("ThankYou", "Home")',
            success: function() {
                ZoomMtg.join(
                    {
                        meetingNumber: meetConfig.meetingNumber,
                        userName: meetConfig.userName,
                        signature: signature,
                        apiKey: meetConfig.apiKey,
                        passWord: meetConfig.passWord,
                        success: function(res) {
                            // $('#nav-tool').hide();
                            console.log('join meeting success');
                        },
                        error: function(res) {
                            console.log(res);
                        }
                    }
                );
            },
            error: function(res) {
                console.log(res);
            }
        });
    }
</script>

Demo.Zoom.Web/Views/Zoom/Webinar.cshtml
@model Demo.Zoom.Web.Models.ZoomConfigurationModel
@{
    ViewBag.Title = "Index";
}
@* Bootstrap form template : https://bootsnipp.com/snippets/nNZ47*@
<link href="~/Content/zoom.css" rel="stylesheet" />
<div class="container-fluid">
    <div class="container">
        <div id="formMeeting" class="formBox">
            <form>
                <div class="row">
                    <div class="col-sm-12">
                        <h1>Join Webinar</h1>
                    </div>
                </div>

                <div class="row">
                    <div class="col-sm-6">
                        <div class="inputBox ">
                            <div class="inputText">User Name</div>
                            <input type="text" name="display_name" id="display_name" class="input">
                        </div>
                    </div>

                    <div class="col-sm-6">
                        <div class="inputBox">
                            <div class="inputText">User Email</div>
                            <input type="text" name="user_email" id="user_email" class="input">
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-sm-6">
                        <div class="inputBox">
                            <div class="inputText">Webinar Number</div>
                            <input type="text" name="meeting_number" id="meeting_number" class="input">
                        </div>
                    </div>

                    <div class="col-sm-6">
                        <div class="inputBox">
                            <div class="inputText">Webinar Password</div>
                            <input type="text" name="meeting_pwd" id="meeting_pwd" class="input">
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-sm-12">
                        <label class="inputLabel">Language</label>
                        <div class="inputBox">
                            <select id="meeting_lang" class="sdk-select">
                                <option value="en-US">English</option>
                                <option value="de-DE">German Deutsch</option>
                                <option value="es-ES">Spanish Español</option>
                                <option value="fr-FR">French Français</option>
                                <option value="jp-JP">Japanese 日本語</option>
                                <option value="pt-PT">Portuguese Portuguese</option>
                                <option value="ru-RU">Russian Русский</option>
                                <option value="zh-CN">Chinese 简体中文</option>
                                <option value="zh-TW">Chinese 繁体中文</option>
                                <option value="ko-KO">Korean 한국어</option>
                            </select>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-sm-12">
                        <button type="submit" class="btn btn-primary" id="join_webinar">Join</button>
                        <button type="submit" class="btn btn-primary" id="clear_all">Clear</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

<script src="https://source.zoom.us/1.9.5/lib/vendor/react.min.js"></script>
<script src="https://source.zoom.us/1.9.5/lib/vendor/react-dom.min.js"></script>
<script src="https://source.zoom.us/1.9.5/lib/vendor/redux.min.js"></script>
<script src="https://source.zoom.us/1.9.5/lib/vendor/redux-thunk.min.js"></script>
<script src="https://source.zoom.us/1.9.5/lib/vendor/lodash.min.js"></script>

<script src="https://source.zoom.us/zoom-meeting-1.9.5.min.js"></script>

<script src="~/Scripts/zoom/tool.js"></script>
<script src="~/Scripts/zoom/index.js"></script>
<script type="text/javascript">
    $(".input").focus(function() {
        $(this).parent().addClass("focus");
    });
    var API_KEY = '@Model.ApiKey';
    var API_SECRET = '@Model.ApiSecret';

    document.getElementById('join_webinar').addEventListener('click',
        function(e) {

            e.preventDefault();

            if (!this.form.checkValidity()) {
                alert("Enter Name and Meeting Number");
                return false;
            }

            //testTool.setCookie("meeting_number", meetConfig.meetingNumber);
            //testTool.setCookie("meeting_pwd", meetConfig.passWord);

            var meetConfig = {
                apiKey: API_KEY,
                apiSecret: API_SECRET,
                meetingNumber: parseInt(document.getElementById('meeting_number').value),
                userName: document.getElementById('display_name').value,
                userEmail: document.getElementById('user_email').value,
                passWord: document.getElementById('meeting_pwd').value,
                leaveUrl: '@Url.Action("Index", "Home")',
                role: 0
            };

            GetSignature(meetConfig.meetingNumber, meetConfig.role).then(function(data) {
                //console.log(data);
                JoinMeeting(meetConfig, data.result);
            });

        });

    document.getElementById('clear_all').addEventListener('click',
        function(e) {
            testTool.deleteAllCookies();
            document.getElementById('display_name').value = '';
            document.getElementById('meeting_number').value = '';
            document.getElementById('meeting_pwd').value = '';
            document.getElementById('user_email').value = '';
            document.getElementById('meeting_lang').value = 'en-US';
        });

    function GetSignature(meetingId, roleId) {
        return $.ajax({
            url: '@Url.Action("GetSignature", "Zoom")',
            type: 'GET',
            dataType: 'json',
            cache: false,
            data: { 'meetingId': meetingId, 'roleId': roleId }
        });
    }

    function JoinMeeting(meetConfig, signature) {
        //console.log('meetConfig', meetConfig);
        //console.log('signature', signature);

        ZoomMtg.init({
            leaveUrl: '@Url.Action("ThankYou", "Home")',
            success: function() {
                ZoomMtg.join(
                    {
                        meetingNumber: meetConfig.meetingNumber,
                        userName: meetConfig.userName,
                        signature: signature,
                        apiKey: meetConfig.apiKey,
                        passWord: meetConfig.passWord,
                        userEmail: meetConfig.userEmail,
                        success: function(res) {
                            // $('#nav-tool').hide();
                            console.log('join meeting success');
                        },
                        error: function(res) {
                            console.log(res);
                        }
                    }
                );
            },
            error: function(res) {
                console.log(res);
            }
        });
    }
</script>